### ISSUE TITLE
sync with maven central

### ISSUE THREAD

**Issue by Kidlike** [Monits/findbugs-plugin#17]
Thanks for the 0.2.0 release!

Would it be possible to [sync with maven central](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html) ?

My company is in a regulated environment (pharmaceuticals), and moving from maven central to jcenter would be a big decision, because of the paperwork and validation involved in the process.

**Comment by jsotuyod** [comment]
I've just applied to be able to publish there. Hopefully will be done in a couple days... Will keep you posted.

I went to jcenter initially because of ease of use / your complain was regarding repository speed; but I'll try it if it's important for you guys.

**Comment by Kidlike** [comment]
Cheers, appreciated :)

**Comment by jsotuyod** [comment]
It appears to be ready, much faster than anticipated. It may take some time for servers to sync though, but you can see it listed [here](https://oss.sonatype.org/content/repositories/releases/com/monits/findbugs-plugin/0.2.0/)

**Comment by jsotuyod** [comment]
[It's synced](https://repo.maven.apache.org/maven2/com/monits/findbugs-plugin/0.2.0/)! Let me know if you need anything else!

**Comment by Kidlike** [comment]
Thanks so much! :)
